//! Cookie header construction for YouTube login.
//!
//! Cookies reach us two ways: read straight out of a browser's own database
//! (see [`crate::browser_cookies`]) or pasted by the user as a raw header /
//! Netscape `cookies.txt`. Both funnel into [`cookie_header_from_pairs`].
//!
//! Security: cookie material is never logged and never rendered.

use anyhow::{bail, Context, Result};

/// Build a `name=value; ..` Cookie header from Netscape cookies.txt text.
///
/// We parse this ourselves rather than handing the file to rustypipe:
/// its parser only accepts rows whose domain is exactly `.youtube.com`
/// (dropping host-only rows) and rejects the whole file on any short line,
/// which some browser exports contain.
pub fn cookie_header_from_netscape(text: &str) -> Result<String> {
    let mut pairs: Vec<(String, String)> = Vec::new();
    for raw in text.lines() {
        let line = raw.strip_prefix("#HttpOnly_").unwrap_or(raw).trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let cols: Vec<&str> = line.split('\t').collect();
        if cols.len() < 7 {
            continue; // tolerate malformed rows instead of failing the import
        }
        let domain = cols[0].trim_start_matches('.');
        if domain != "youtube.com" && !domain.ends_with(".youtube.com") {
            continue;
        }
        let (name, value) = (cols[5].trim(), cols[6].trim());
        pairs.push((name.to_string(), value.to_string()));
    }
    cookie_header_from_pairs(pairs)
}

/// Build a Cookie header from already-extracted `(name, value)` pairs.
///
/// Shared by the cookies.txt path and the native browser reader.
pub fn cookie_header_from_pairs(pairs: Vec<(String, String)>) -> Result<String> {
    let mut out: Vec<(String, String)> = Vec::new();
    for (name, value) in pairs {
        if name.is_empty() || out.iter().any(|(n, _)| *n == name) {
            continue; // first occurrence wins
        }
        out.push((name, value));
    }
    if out.is_empty() {
        bail!("没有找到 YouTube 的登录信息");
    }

    // Request signing (SAPISIDHASH) reads the `SAPISID` cookie by name.
    // Some profiles - Firefox in particular - only carry the equivalent
    // `__Secure-*PAPISID` value, so mirror it under the expected name;
    // without this the requests silently go out unauthenticated.
    if !out.iter().any(|(n, _)| n == "SAPISID") {
        if let Some(value) = ["__Secure-3PAPISID", "__Secure-1PAPISID"]
            .iter()
            .find_map(|alias| {
                out.iter()
                    .find(|(n, v)| n == alias && !v.is_empty())
                    .map(|(_, v)| v.clone())
            })
        {
            out.push(("SAPISID".to_string(), value));
        }
    }

    Ok(out
        .into_iter()
        .map(|(n, v)| format!("{n}={v}"))
        .collect::<Vec<_>>()
        .join("; "))
}

/// Does this cookie header carry the credential requests are signed with?
/// Checked by name because that is how the signing code looks it up.
pub fn has_auth_credential(header: &str) -> bool {
    header
        .split(';')
        .filter_map(|c| c.trim().split_once('='))
        .any(|(name, value)| name == "SAPISID" && !value.is_empty())
}

/// Open a URL in the user's default browser (so they can log in first).
pub fn open_in_browser(url: &str) -> Result<()> {
    #[cfg(windows)]
    let mut cmd = {
        let mut c = std::process::Command::new("cmd");
        // The empty "" is the window title arg `start` expects before the URL.
        c.args(["/C", "start", "", url]);
        use std::os::windows::process::CommandExt;
        c.creation_flags(0x0800_0000);
        c
    };
    #[cfg(target_os = "macos")]
    let mut cmd = {
        let mut c = std::process::Command::new("open");
        c.arg(url);
        c
    };
    #[cfg(all(unix, not(target_os = "macos")))]
    let mut cmd = {
        let mut c = std::process::Command::new("xdg-open");
        c.arg(url);
        c
    };

    cmd.stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .spawn()
        .context("无法打开浏览器")?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Rows mirror real browser-export output: header comments, a `#HttpOnly_`
    /// prefix, unrelated domains, a subdomain row, and a short line.
    const SAMPLE: &str = "# Netscape HTTP Cookie File\n\
         # This file is generated by yt-dlp.\n\
         \n\
         .google.com\tTRUE\t/\tTRUE\t0\tSAPISID\tgoogle-value\n\
         #HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t0\tSAPISID\tyt-value\n\
         .youtube.com\tTRUE\t/\tTRUE\t0\tLOGIN_INFO\tinfo\n\
         music.youtube.com\tFALSE\t/\tTRUE\t0\tPREF\tpref-value\n\
         truncated-line\n";

    #[test]
    fn netscape_parser_keeps_youtube_cookies_only() {
        let header = cookie_header_from_netscape(SAMPLE).expect("should parse");
        assert!(header.contains("SAPISID=yt-value"));
        assert!(header.contains("LOGIN_INFO=info"));
        // Host-only subdomain rows count too (rustypipe's parser drops them).
        assert!(header.contains("PREF=pref-value"));
        // Other domains never leak in, even with the same cookie name.
        assert!(!header.contains("google-value"));
    }

    #[test]
    fn netscape_parser_reports_when_no_youtube_cookies() {
        let only_other = ".google.com\tTRUE\t/\tTRUE\t0\tSAPISID\tv\n";
        assert!(cookie_header_from_netscape(only_other).is_err());
    }

    #[test]
    fn auth_credential_detection() {
        assert!(has_auth_credential("SAPISID=abc; PREF=x"));
        // Present but empty is not a credential.
        assert!(!has_auth_credential("SAPISID=; PREF=x"));
        // Logged-out profiles carry these but cannot authenticate.
        assert!(!has_auth_credential("VISITOR_INFO1_LIVE=x; YSC=y; PREF=z"));
        // The alias alone is not what the signing code looks up.
        assert!(!has_auth_credential("__Secure-3PAPISID=abc"));
    }

    #[test]
    fn secure_papisid_is_mirrored_as_sapisid() {
        // Firefox profiles often carry only the __Secure- variant; requests
        // would go out unauthenticated without this mapping.
        let firefox_style = ".youtube.com\tTRUE\t/\tTRUE\t0\t__Secure-3PAPISID\tsecret\n\
             .youtube.com\tTRUE\t/\tTRUE\t0\tSID\tsid-value\n";
        let header = cookie_header_from_netscape(firefox_style).unwrap();
        assert!(header.contains("SAPISID=secret"));
        assert!(has_auth_credential(&header));
    }

    #[test]
    fn existing_sapisid_is_not_overwritten() {
        let both = ".youtube.com\tTRUE\t/\tTRUE\t0\tSAPISID\treal\n\
                    .youtube.com\tTRUE\t/\tTRUE\t0\t__Secure-3PAPISID\talias\n";
        let header = cookie_header_from_netscape(both).unwrap();
        assert!(header.contains("SAPISID=real"));
        assert!(
            !header.contains("SAPISID=alias"),
            "real value was clobbered"
        );
        assert!(
            header.contains("__Secure-3PAPISID=alias"),
            "alias was dropped"
        );
    }

    /// The native reader hands over raw pairs; dedup and the SAPISID mirror
    /// must behave the same on that path.
    #[test]
    fn pairs_path_dedupes_and_mirrors() {
        let pairs = vec![
            ("SID".to_string(), "first".to_string()),
            ("SID".to_string(), "second".to_string()),
            ("__Secure-1PAPISID".to_string(), "alias".to_string()),
        ];
        let header = cookie_header_from_pairs(pairs).unwrap();
        assert!(header.contains("SID=first"));
        assert!(!header.contains("second"), "duplicate won over the first");
        assert!(header.contains("SAPISID=alias"));
    }
}
